### ISSUE TITLE
Limit to 20 preloads

### ISSUE THREAD

**Issue by twifkak** [google/webpackager#59]
The Google SXG cache has a [limit of 20 preloads](https://github.com/google/webpackager/blob/master/docs/cache_requirements.md#user-content-google-sxg-cache:~:text=There%20may%20be%20no%20more%20than%2020%20rel%3Dpreloads.). I don't see anything in the webpackager code that guarantees that requirement is met. (Did I miss it?) We should provide a [default enabled] option to do so.

Seems especially necessary given the optional HTMLTask to [promote preload tags to headers](https://github.com/google/webpackager/blob/master/processor/htmlproc/htmltask/preload.go), where the former are more prominent today, with no such limit.

**Comment by yuizumi** [comment]
We don't have logic to limit the preloads to 20 (or any number), as far as I can recall. One easy approach is maybe to write a [common processor](https://github.com/google/webpackager/tree/master/processor/commonproc) to cut off `Preloads` (of `exchange.Response`) to the given limit, then register it as a [postprocessor](https://github.com/google/webpackager/blob/master/processor/complexproc/complexproc.go#L49).

There's also a processor that propagates preload headers. ([code](https://github.com/google/webpackager/blob/master/processor/commonproc/preload.go))
